### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by fjtrujy** [pspdev/libpspme#1]
Let's use this as the TODO list stuff
 stuff:
- [X] Create repository
- [X] Create a project in `pspdev`
- [ ] Create the skeleton of the library (using `cmake`)
- [ ] Create the most basic ME implementation (`.a` + `.prx` )
- [ ] Create a dummy sample  about how to use it
- [ ] Create some basic documentation
- [ ] Create CI/CD
- [ ] Add package into `psp-packages`
- [ ] Embedd the PRX into the `.a` to make integration easier

**Comment by fjtrujy** [comment]
> Create the skeleton of the library (using `cmake`)
This is almost done already however the `cmake` stuff is not ready to generate module `PRX` files.
Some additional work in `pspsdk` is needed.
